apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins
  name: jenkins-deployer-role
rules:
- apiGroups: ["", "apps", "networking.k8s.io", "gateway.networking.k8s.io"] 
  resources: ["pods", "deployments", "statefulsets", "serviceaccounts", "configmaps","jobs", "cronjobs", "ingresses", "networkpolicies", "persistenvolumeclaims", "gateways", "httproutes"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"] 

