apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: food-app
build:
  artifacts:
    - image: gabeodame/auth-service
      context: auth
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: gabeodame/recipe-client
      context: client
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: mongo
      context: recipe
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
    - infra/k8s/auth-config.yaml
    - infra/k8s/auth-depl.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/auth-mongo-secret.yaml
    - infra/k8s/auth-mongo-srv.yaml
    - infra/k8s/auth-srv.yaml
    - infra/k8s/client-depl.yaml
    - infra/k8s/client-srv.yaml
