apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: food-app
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  local:
    push: false # No need to push images for local development
    useBuildkit: true
  artifacts:
    - image: gabeodame/auth-service
      context: services/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gabeodame/recipe-client
      context: services/client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "app/**/*.ts"
            dest: .
    - image: gabeodame/recipe-backend
      context: services/recipe
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gabeodame/userprofile-backend
      context: services/profile
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/base/namespace.yaml
    - ./infra/k8s/base/network.yaml
    - ./infra/k8s/dev/secrets/auth-mongo-secret.yaml
    - ./infra/k8s/dev/secrets/recipe-postgres-secret.yaml
    - ./infra/k8s/dev/secrets/userprofile-psql-secret.yaml
    - ./infra/k8s/dev/secrets/rabbitmq-secret.yaml
    - ./infra/k8s/dev/statefulsets/rabbitmq-sts.yaml
    - ./infra/k8s/dev/statefulsets/auth-mongo-sts.yaml
    - ./infra/k8s/dev/statefulsets/recipe-postgres-sts.yaml
    - ./infra/k8s/dev/statefulsets/userprofile-sts.yaml
    - ./infra/k8s/dev/deployments/*.yaml
    - ./infra/k8s/dev/ingress/*.yaml
profiles:
  - name: dev
    activation:
      - kubeContext: docker-desktop # Activate for Docker Desktop Kubernetes
    build:
      local:
        push: false # Keep images local
    deploy:
      kubectl: {}
    manifests:
      rawYaml:
        - ./infra/k8s/base/namespace.yaml
        - ./infra/k8s/base/network.yaml
        - ./infra/k8s/dev/secrets/auth-mongo-secret.yaml
        - ./infra/k8s/dev/secrets/recipe-postgres-secret.yaml
        - ./infra/k8s/dev/secrets/userprofile-psql-secret.yaml
        - ./infra/k8s/dev/secrets/rabbitmq-secret.yaml
        - ./infra/k8s/dev/statefulsets/rabbitmq-sts.yaml
        - ./infra/k8s/dev/statefulsets/auth-mongo-sts.yaml
        - ./infra/k8s/dev/statefulsets/recipe-postgres-sts.yaml
        - ./infra/k8s/dev/statefulsets/userprofile-sts.yaml
        - ./infra/k8s/dev/deployments/*.yaml
        - ./infra/k8s/dev/ingress/*.yaml

  - name: prod
    build:
      local:
        push: true # Push images to remote registry
      artifacts:
        - image: gabeodame/auth-service
        - image: gabeodame/recipe-client
        - image: gabeodame/recipe-backend
        - image: gabeodame/userprofile-backend
    deploy:
      kubectl: {}
    manifests:
      rawYaml:
        - ./infra/k8s/prod/*.yaml

