apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: food-app
build:
  artifacts:
    - image: gabeodame/auth-service
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gabeodame/recipe-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "app/**/*.ts"
            dest: .
    - image: gabeodame/recipe-backend
      context: recipe
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
