apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: food-app
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  local:
    push: false # No need to push images for local development
    useBuildkit: true
  artifacts:
    - image: gabeodame/auth-service
      context: services/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gabeodame/recipe-client
      context: services/client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "app/**/*.ts"
            dest: .
    - image: gabeodame/recipe-backend
      context: services/recipe
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gabeodame/userprofile-backend
      context: services/profile
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gabeodame/ingredient-backend
      context: services/ingredient
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gabeodame/uploads-backend
      context: services/uploads
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
deploy:
  helm:
    releases:
      - name: food-app
        chartPath: infra/helm/food-app
        namespace: recipe
        createNamespace: true
        valuesFiles:
          - infra/helm/food-app/values-dev.yaml
        setValueTemplates:
          global.imageTag: "{{.IMAGE_TAG_gabeodame_auth_service}}"
profiles:
  - name: dev
    activation:
      - kubeContext: docker-desktop # Activate for Docker Desktop Kubernetes
    deploy:
      helm:
        releases:
          - name: food-app
            chartPath: infra/helm/food-app
            namespace: recipe
            createNamespace: true
            valuesFiles:
              - infra/helm/food-app/values-dev.yaml
            setValueTemplates:
              global.imageTag: "{{.IMAGE_TAG_gabeodame_auth_service}}"
        hooks:
          before:
            - host:
                command:
                  - sh
                  - -c
                  - kubectl apply -f infra/k8s/dev/secrets
    build:
      local:
        push: false # Keep images local

  - name: staging
    build:
      local:
        push: true
    deploy:
      helm:
        releases:
          - name: food-app
            chartPath: infra/helm/food-app
            namespace: recipe
            createNamespace: true
            valuesFiles:
              - infra/helm/food-app/values-staging.yaml
            setValueTemplates:
              global.imageTag: "{{.IMAGE_TAG_gabeodame_auth_service}}"

  - name: prod
    build:
      local:
        push: true # Push images to remote registry
      artifacts:
        - image: gabeodame/auth-service
        - image: gabeodame/recipe-client
        - image: gabeodame/recipe-backend
        - image: gabeodame/userprofile-backend
        - image: gabeodame/ingredient-backend
        - image: gabeodame/uploads
    deploy:
      helm:
        releases:
          - name: food-app
            chartPath: infra/helm/food-app
            namespace: recipe
            createNamespace: true
            valuesFiles:
              - infra/helm/food-app/values-prod.yaml
            setValueTemplates:
              global.imageTag: "{{.IMAGE_TAG_gabeodame_auth_service}}"
