apiVersion: v1
kind: Secret
metadata:
  namespace: recipe
  name: s3-secret
type: Opaque
stringData:
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: "changeme"
  AWS_SECRET_ACCESS_KEY: "changeme"
  AWS_S3_BUCKET: "changeme"
