export const units: Record<string, string[]> = {
  metric: [
    "milliliters (ml)",
    "centiliters (cl)",
    "deciliters (dl)",
    "liters (l)",
    "milligrams (mg)",
    "grams (g)",
    "kilograms (kg)",
  ],
  imperial: [
    "teaspoons (tsp)",
    "tablespoons (tbsp)",
    "fluid ounces (fl oz)",
    "cups",
    "pints (pt)",
    "quarts (qt)",
    "gallons (gal)",
    "ounces (oz)",
    "pounds (lb)",
  ],
  cooking: [
    "drops",
    "pinches",
    "dashes",
    "smidgens",
    "handfuls",
    "cloves",
    "bunches",
    "slices",
    "sticks (butter)",
    "sprigs",
    "heads (e.g., lettuce, garlic)",
  ],
  bakery: [
    "grains",
    "sheets",
    "scoops",
    "bars",
    "eggs",
    "loaves",
    "pieces",
    "squares",
    "layers (cake)",
    "rolls",
  ],
  generic: [
    "pieces",
    "slices",
    "chunks",
    "whole",
    "halves",
    "quarters",
    "wedges",
    "rounds",
    "stalks",
    "pods",
    "rolls",
  ],
  custom: [],
};
