apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: recipe
  labels:
    app: uploads-service
  name: uploads-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploads-service
  template:
    metadata:
      labels:
        app: uploads-service
    spec:
      containers:
        - name: uploads-service
          image: gabeodame/uploads-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_S3_BUCKET


--- 

apiVersion: v1
kind: Service
metadata:
  namespace: recipe
  labels:
    app: uploads-service
  name: uploads-service
spec:
  selector:
    app: uploads-service # Must match the app label in the Deployment
  ports:
    - name: http
      protocol: TCP
      port: 3000 # The port exposed by the service
      targetPort: 3000 # The container port defined in the Deployment
  type: ClusterIP
