apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: recipe
  labels:
    app: auth-service
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.34
          command:
            - sh
            - "-c"
            - |
              echo "Waiting for MongoDB to be ready..."
              until nc -z auth-mongo-headless 27017; do
                echo "MongoDB not ready, retrying in 1s..."
                sleep 1
              done
              echo "MongoDB is ready!"
      containers:
        - name: auth-service
          image: gabeodame/auth-service
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
      volumes:
        - name: init-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  namespace: recipe
  labels:
    app: auth-service
  name: auth-service
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: auth-service
