apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: recipe
  labels:
    app: auth-service
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.34
          command:
            - sh
            - "-c"
            - |
              echo "Waiting for MongoDB to be ready..."
              until nc -z auth-mongo-headless 27017; do
                echo "MongoDB not ready, retrying in 1s..."
                sleep 1
              done
              echo "MongoDB is ready!"
      containers:
        - name: auth-service
          image: gabeodame/auth-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_URL
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "125m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "250m"


---


apiVersion: v1
kind: Service
metadata:
  namespace: recipe
  labels:
    app: auth-service
  name: auth-service
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: auth-service
