apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: recipe
  labels:
    app: recipe-client
  name: recipe-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-client
  template:
    metadata:
      labels:
        app: recipe-client
    spec:
      containers:
        - image: gabeodame/recipe-client
          name: recipe-client
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "125m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "250m"


---
apiVersion: v1
kind: Service
metadata:
  namespace: recipe
  labels:
    app: recipe-client
  name: recipe-client-service
spec:
  ports:
    - name: client
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: recipe-client
  type: ClusterIP
