apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: recipe
  labels:
    app: ingredient
  name: ingredient-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingredient
  template:
    metadata:
      labels:
        app: ingredient
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq-service 5672; do echo waiting for rabbitmq; sleep 2; done;']

      containers:
        - name: ingredient
          image: gabeodame/ingredient-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: ingredient-postgres-secret
                  key: DB_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: ingredient-postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ingredient-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ingredient-postgres-secret
                  key: POSTGRES_PASSWORD          
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ingredient-postgres-secret
                  key: DATABASE_URL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: ingredient-postgres-secret
                  key: NODE_ENV
            - name: DB_SYNCHRONIZE
              valueFrom:
                secretKeyRef:
                  name: ingredient-postgres-secret
                  key: DB_SYNCHRONIZE

            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: ingredient-postgres-secret
                  key: RABBITMQ_URL
          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "1Gi"
          #     cpu: "500m"


---

apiVersion: v1
kind: Service
metadata:
  namespace: recipe
  labels:
    app: ingredient
  name: ingredient-service
spec:
  selector:
    app: ingredient 
  ports:
    - name: http
      protocol: TCP
      port: 3000 
      targetPort: 3000 
  type: ClusterIP
