apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-aws-sc
  namespace: recipe
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete # Adjust according to needs: Retain or Delete
parameters:
  type: gp2
  encrypted: "true" # Optional encryption
  fsType: ext4
