apiVersion: v1
kind: Secret
data:
  postgres-db: cmVjaXBl
  postgres-password: cGFzc3dvcmQ=
  postgres-user: Z2FiZW9kYW1l
  database-url: cG9zdGdyZXNxbDovL2dhYmVvZGFtZTpwYXNzd29yZEByZWNpcGUtcG9zdGdyZXMtc2VydmljZTo1NDMyL3JlY2lwZQo=
type: Opaque
metadata:
  namespace: recipe
  creationTimestamp: null
  name: recipe-postgres-secret
