apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: auth-srv
  name: auth-srv
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: auth
  type: ClusterIP
status:
  loadBalancer: {}
