apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-03-12T13:44:54Z"
  labels:
    app: auth-service
  name: auth-service
  resourceVersion: "4157206"
  uid: 6fe5ec40-13fe-452f-a9cd-3efdeca1b94e
spec:
  clusterIP: 10.99.50.88
  clusterIPs:
    - 10.99.50.88
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: auth-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
