apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: recipe-client
  name: recipe-client-srv
spec:
  ports:
    - name: 80-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: recipe-client
  type: ClusterIP
status:
  loadBalancer: {}
