apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: recipe-client
  name: recipe-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: recipe-client
    spec:
      containers:
        - image: gabeodame/recipe-client:1.0.0
          name: recipe-client
          resources: {}
status: {}
