apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: recipe-client
  name: recipe-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-client
  template:
    metadata:
      labels:
        app: recipe-client
    spec:
      containers:
        - image: gabeodame/recipe-client:1.0.1
          name: recipe-client
