apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: recipe
  labels:
    app: recipe
  name: recipe-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe
  template:
    metadata:
      labels:
        app: recipe
    spec:
      initContainers:
        - name: db-check-and-seed
          image: gabeodame/recipe-backend:1.0.0
          command: ["/bin/sh", "-c"]
          args:
            - >
              until nc -z recipe-postgres-service 5432; do
                echo 'Waiting for PostgreSQL to become ready...';
                sleep 2;
              done;
              echo 'PostgreSQL is ready, running seed operation...';
              npx prisma migrate deploy &&
              npx prisma db seed
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: recipe-postgres-secret
                  key: database-url
      containers:
        - image: gabeodame/recipe-backend:1.0.0
          name: recipe
          env: # This line is correctly indented now
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: recipe-postgres-secret
                  key: database-url
---
apiVersion: v1
kind: Service
metadata:
  namespace: recipe
  labels:
    app: recipe
  name: recipe-service
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: recipe
  type: ClusterIP
