apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: recipe
  labels:
    app: auth-mongo
  name: auth-mongo
spec:
  serviceName: auth-mongo-headless
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongo
  template:
    metadata:
      labels:
        app: auth-mongo
    spec:
      containers:
        - name: auth-mongo
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          ports:
            - containerPort: 27017
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  namespace: recipe
  labels:
    app: auth-mongo
  name: auth-mongo-headless
spec:
  clusterIP: None
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: auth-mongo
