apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: recipe
  labels:
    app: recipe-postgres
  name: recipe-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-postgres
  serviceName: recipe-postgres-headless
  template:
    metadata:
      labels:
        app: recipe-postgres
    spec:
      containers:
        - image: postgres:15
          name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: recipe-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recipe-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: recipe-postgres-secret
                  key: POSTGRES_DB
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          # readinessProbe:
          #   exec:
          #     command:
          #       - pg_isready
          #       - -U
          #       - gabeodame
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   exec:
          #     command:
          #       - pg_isready
          #       - -U
          #       - gabeodame
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi


---
apiVersion: v1
kind: Service
metadata:
  namespace: recipe
  labels:
    app: recipe-postgres
  name: recipe-postgres-headless
spec:
  clusterIP: None # Headless service for StatefulSet
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: recipe-postgres

