apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: recipe
  labels:
    app: recipe-postgres
  name: recipe-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-postgres
  serviceName: recipe-postgres-headless
  template:
    metadata:
      labels:
        app: recipe-postgres
    spec:
      containers:
        - image: postgres
          name: postgres
          env:
            - name: POSTGRES_USER
              value: "gabeodame"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recipe-postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              value: "recipe"
            # Setting PGDATA to point to the subdirectory
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  namespace: recipe
  labels:
    app: recipe-postgres
  name: recipe-postgres-headless
spec:
  clusterIP: None # This creates a headless service, which is necessary for StatefulSets
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: recipe-postgres
