apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: userprofile-postgres
  namespace: recipe
  labels:
    app: userprofile-postgres
spec:
  serviceName: userprofile-postgres-headless
  replicas: 1
  selector:
    matchLabels:
      app: userprofile-postgres
  template:
    metadata:
      labels:
        app: userprofile-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: userprofile-postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: userprofile-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userprofile-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "1Gi"
          #     cpu: "500m"
          # readinessProbe:
          #   exec:
          #     command:
          #       - pg_isready
          #       - -U
          #       - gabeodame
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   exec:
          #     command:
          #       - pg_isready
          #       - -U
          #       - gabeodame
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]

        resources:
          requests:
            storage: 1Gi


---

apiVersion: v1
kind: Service
metadata:
  name: userprofile-postgres-headless
  namespace: recipe
  labels:
    app: userprofile-postgres
spec:
  clusterIP: None # Headless service for StatefulSet
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: userprofile-postgres
